// Generated from the DM-Screen project's SRD item list (marilynjay/dm-screen,
// src/app.jsx ITEMS_RAW), enriched with SRD 5.1 attunement flags and standard
// weights. Regenerate rather than hand-editing entries wholesale; one-off
// fixes inline are fine.
export interface ItemStats {
  dmg?: string;
  dtype?: string;
  bonus?: number;
  properties?: string;
  ac?: string;
  armorClass?: string;
  stealthDis?: boolean;
  strReq?: string;
  heal?: string;
  charges?: number;
  chargesMax?: number;
  recharge?: string;
  spellLevel?: string;
  dc?: string;
  capacity?: string;
  language?: string;
  cursed?: boolean;
  curseText?: string;
  spells?: string; // one per line: "Cure Wounds — 1"
}

export interface CatalogItem {
  name: string;
  category: string;
  subtype: string;
  rarity: string;
  magic: boolean;
  requiresAttunement: boolean;
  weight: number | null;
  value?: string; // list price, mundane gear mostly ("1 gp")
  stats?: ItemStats;
  rules: string;
}

export const CATALOG: CatalogItem[] = [
  { name: "Alchemy Jug", category: "supplies", subtype: "container", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 12, rules: "Produces a chosen liquid each day (water, mayonnaise, acid…)." },
  { name: "Ammunition, +1 (each)", category: "gear", subtype: "ammunition", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "+1 to attack and damage; bonus lost after hit." },
  { name: "Amulet of Health", category: "accessory", subtype: "amulet", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Constitution becomes 19." },
  { name: "Amulet of Proof against Detection and Location", category: "accessory", subtype: "amulet", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Wearer hidden from divination magic." },
  { name: "Amulet of the Planes", category: "accessory", subtype: "amulet", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Plane Shift (DC 15 INT to arrive on target)." },
  { name: "Animated Shield", category: "gear", subtype: "shield", rarity: "very rare", magic: true, requiresAttunement: true, weight: 6, stats: {"ac":"+2"}, rules: "Bonus action: shield floats and guards you hands-free." },
  { name: "Armor of Resistance", category: "gear", subtype: "armor", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Resistance to one damage type while worn." },
  { name: "Armor, +1", category: "gear", subtype: "armor", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "+1 bonus to AC." },
  { name: "Armor, +2", category: "gear", subtype: "armor", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "+2 bonus to AC." },
  { name: "Armor, +3", category: "gear", subtype: "armor", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "+3 bonus to AC." },
  { name: "Bag of Beans", category: "supplies", subtype: "container", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"charges":6,"chargesMax":6}, rules: "Plant a bean: wildly random magical effect." },
  { name: "Bag of Holding", category: "supplies", subtype: "container", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 15, stats: {"capacity":"500 lb"}, rules: "Holds 500 lb in an extradimensional space." },
  { name: "Bag of Tricks", category: "supplies", subtype: "container", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Pull a fuzzy object: becomes a random beast until dawn." },
  { name: "Battleaxe", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Martial melee — versatile (1d10)." },
  { name: "Bead of Force", category: "consumable", subtype: "alchemical", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Throw: 5d4 force + sphere imprisons, DC 15 DEX." },
  { name: "Belt of Dwarvenkind", category: "accessory", subtype: "belt", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "CON +2 (max 20), dwarven traits, ADV vs. poison." },
  { name: "Belt of Fire Giant Strength", category: "accessory", subtype: "belt", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Strength becomes 25." },
  { name: "Blowgun", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 1, stats: {"dmg":"1","dtype":"piercing"}, rules: "Martial ranged 25/100." },
  { name: "Boots of Elvenkind", category: "accessory", subtype: "boots", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Steps make no sound; ADV on Stealth to move silently." },
  { name: "Boots of Levitation", category: "accessory", subtype: "boots", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Levitate on self at will." },
  { name: "Boots of Speed", category: "accessory", subtype: "boots", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Click heels: double speed, no opportunity attacks (10 min/day)." },
  { name: "Boots of Striding and Springing", category: "accessory", subtype: "boots", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Speed 30 ft; jump distance ×3." },
  { name: "Bracers of Archery", category: "accessory", subtype: "gloves", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Proficiency with bows; +2 damage with them." },
  { name: "Bracers of Defense", category: "accessory", subtype: "gloves", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "+2 AC while unarmored and shieldless." },
  { name: "Breastplate", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 20, stats: {"ac":"14 + Dex (max 2)","armorClass":"medium"}, rules: "Medium armor — AC 14 + DEX (max 2)." },
  { name: "Brooch of Shielding", category: "accessory", subtype: "amulet", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Immune to Magic Missile; resist force damage." },
  { name: "Cape of the Mountebank", category: "accessory", subtype: "cloak", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cast Dimension Door once per dawn." },
  { name: "Carpet of Flying", category: "other", subtype: "", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Flying carpet, up to 80 ft speed." },
  { name: "Chain Mail", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 55, stats: {"ac":"16","armorClass":"heavy"}, rules: "Heavy armor — AC 16; STR 13; Stealth DIS." },
  { name: "Chain Shirt", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 20, stats: {"ac":"13 + Dex (max 2)","armorClass":"medium"}, rules: "Medium armor — AC 13 + DEX (max 2)." },
  { name: "Chime of Opening", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"charges":10,"chargesMax":10}, rules: "Strike: opens one lock/latch within 120 ft (10 uses)." },
  { name: "Circlet of Blasting", category: "accessory", subtype: "headwear", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast Scorching Ray (+5) once per dawn." },
  { name: "Cloak of Arachnida", category: "accessory", subtype: "cloak", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Spider climb, resist poison, cast Web, immune to webs." },
  { name: "Cloak of Displacement", category: "accessory", subtype: "cloak", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Attacks against you have DIS until you take damage." },
  { name: "Cloak of Elvenkind", category: "accessory", subtype: "cloak", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Hood up: ADV on Stealth; sight checks to spot you have DIS." },
  { name: "Cloak of Invisibility", category: "accessory", subtype: "cloak", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Hood up: Invisible (2 hours of use per day)." },
  { name: "Cloak of Protection", category: "accessory", subtype: "cloak", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "+1 AC and saving throws while worn." },
  { name: "Cloak of the Bat", category: "accessory", subtype: "cloak", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "ADV on Stealth; fly in dim light; become a bat." },
  { name: "Club", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d4","dtype":"bludgeoning"}, rules: "Simple melee." },
  { name: "Crystal Ball", category: "arcana", subtype: "focus", rarity: "very rare", magic: true, requiresAttunement: true, weight: 3, rules: "Cast Scrying (DC 17) while touching it." },
  { name: "Cube of Force", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":36,"chargesMax":36}, rules: "Barrier cube, 36 charges to power different faces." },
  { name: "Daern's Instant Fortress", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cube grows into an adamantine tower." },
  { name: "Dagger", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 1, stats: {"dmg":"1d4","dtype":"piercing"}, rules: "Simple melee — finesse, thrown 20/60." },
  { name: "Dagger of Venom", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: 1, stats: {"dmg":"1d4","dtype":"piercing","bonus":1}, rules: "+1 dagger; coat blade: DC 15 CON or 2d10 poison + Poisoned." },
  { name: "Dancing Sword", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Bonus action: sword fights on its own nearby." },
  { name: "Dart", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 0.25, stats: {"dmg":"1d4","dtype":"piercing"}, rules: "Simple ranged 20/60 — finesse." },
  { name: "Decanter of Endless Water", category: "supplies", subtype: "container", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Pours stream/geyser of water on command." },
  { name: "Deck of Illusions", category: "other", subtype: "", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, stats: {"charges":34,"chargesMax":34}, rules: "Draw a card: creates an illusory creature." },
  { name: "Defender", category: "gear", subtype: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":3}, rules: "+3 sword; shift up to +3 between attack and AC each turn." },
  { name: "Dimensional Shackles", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Manacles prevent all extradimensional travel." },
  { name: "Dragon Scale Mail", category: "gear", subtype: "armor", rarity: "very rare", magic: true, requiresAttunement: true, weight: 45, rules: "+1 scale mail; ADV vs. dragon fear/breath; resist one element." },
  { name: "Dragon Slayer", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":1}, rules: "+1 sword; +3d6 damage vs. dragons." },
  { name: "Driftglobe", category: "supplies", subtype: "camp gear", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Hovering globe casts Light or Daylight." },
  { name: "Dust of Disappearance", category: "consumable", subtype: "alchemical", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Throw: 10-ft radius of creatures turn Invisible for 2d4 minutes." },
  { name: "Dust of Dryness", category: "consumable", subtype: "alchemical", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Pinch absorbs 15-ft cube of water into a pellet." },
  { name: "Dust of Sneezing and Choking", category: "consumable", subtype: "alchemical", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cloud: DC 15 CON or Incapacitated, suffocating." },
  { name: "Dwarven Plate", category: "gear", subtype: "armor", rarity: "very rare", magic: true, requiresAttunement: false, weight: 65, rules: "+2 plate; reduce forced movement by 10 ft." },
  { name: "Dwarven Thrower", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, stats: {"dmg":"1d8","dtype":"bludgeoning","bonus":3}, rules: "+3 warhammer; thrown 20/60, returns; +1d8 (2d8 vs. giants)." },
  { name: "Elemental Gem", category: "consumable", subtype: "alchemical", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Crush: summon the bound elemental." },
  { name: "Elixir of Health", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: cures disease, poison, and conditions; no HP." },
  { name: "Eversmoking Bottle", category: "supplies", subtype: "container", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Unstopper: 60-ft radius of heavy smoke." },
  { name: "Eyes of the Eagle", category: "accessory", subtype: "headwear", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "ADV on sight-based Perception checks." },
  { name: "Flail", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d8","dtype":"bludgeoning"}, rules: "Martial melee." },
  { name: "Flame Tongue", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Command: flaming blade, +2d6 fire damage." },
  { name: "Frost Brand", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "+1d6 cold sword; resist fire; extinguishes flames." },
  { name: "Gauntlets of Ogre Power", category: "accessory", subtype: "gloves", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Strength becomes 19." },
  { name: "Gem of Seeing", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "3 charges: Truesight 120 ft for 10 min." },
  { name: "Giant Slayer", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":1}, rules: "+1 weapon; +2d6 vs. giants, DC 15 STR or prone." },
  { name: "Glaive", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, stats: {"dmg":"1d10","dtype":"slashing"}, rules: "Martial melee — reach 10 ft, two-handed." },
  { name: "Glamoured Studded Leather", category: "gear", subtype: "armor", rarity: "rare", magic: true, requiresAttunement: false, weight: 13, rules: "+1 studded leather; changes appearance on command." },
  { name: "Gloves of Missile Snaring", category: "accessory", subtype: "gloves", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Reaction: reduce ranged weapon damage by 1d10+DEX; catch at 0." },
  { name: "Goggles of Night", category: "accessory", subtype: "headwear", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Darkvision 60 ft." },
  { name: "Greataxe", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 7, stats: {"dmg":"1d12","dtype":"slashing"}, rules: "Martial melee — two-handed." },
  { name: "Greatclub", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 10, stats: {"dmg":"1d8","dtype":"bludgeoning"}, rules: "Simple melee, two-handed." },
  { name: "Greatsword", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, stats: {"dmg":"2d6","dtype":"slashing"}, rules: "Martial melee — two-handed." },
  { name: "Halberd", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, stats: {"dmg":"1d10","dtype":"slashing"}, rules: "Martial melee — reach 10 ft, two-handed." },
  { name: "Half Plate", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 40, stats: {"ac":"15 + Dex (max 2)","armorClass":"medium"}, rules: "Medium armor — AC 15 + DEX (max 2); Stealth DIS." },
  { name: "Hammer of Thunderbolts", category: "gear", subtype: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: 10, stats: {"dmg":"2d6","dtype":"bludgeoning","bonus":1}, rules: "+1 (or +3 attuned w/ giant items); giant's bane, thunder crack." },
  { name: "Hand Crossbow", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Martial ranged 30/120 — light." },
  { name: "Handaxe", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d6","dtype":"slashing"}, rules: "Simple melee — thrown 20/60." },
  { name: "Hat of Disguise", category: "accessory", subtype: "headwear", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Cast Disguise Self at will." },
  { name: "Headband of Intellect", category: "accessory", subtype: "headwear", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Intelligence becomes 19." },
  { name: "Heavy Crossbow", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 18, stats: {"dmg":"1d10","dtype":"piercing"}, rules: "Martial ranged 100/400 — two-handed." },
  { name: "Helm of Brilliance", category: "accessory", subtype: "headwear", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":10,"chargesMax":10}, rules: "Gem-studded: fire/daylight spells until gems are spent." },
  { name: "Helm of Comprehending Languages", category: "accessory", subtype: "headwear", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast Comprehend Languages at will." },
  { name: "Helm of Teleportation", category: "accessory", subtype: "headwear", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "Cast Teleport (3 charges, 1d3 at dawn)." },
  { name: "Hide Armor", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 12, stats: {"ac":"12 + Dex (max 2)","armorClass":"medium"}, rules: "Medium armor — AC 12 + DEX (max 2)." },
  { name: "Holy Avenger", category: "gear", subtype: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":3}, rules: "+3 sword; +2d10 radiant vs. fiends/undead; aura of saves." },
  { name: "Horn of Blasting", category: "supplies", subtype: "instrument", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Blow: 30-ft cone, 5d6 thunder + Deafened, DC 15 CON." },
  { name: "Horn of Valhalla (Bronze)", category: "supplies", subtype: "instrument", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Blow: summons 4d4+4 berserker spirits (once per week)." },
  { name: "Horseshoes of Speed", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Mount's speed +30 ft." },
  { name: "Immovable Rod", category: "arcana", subtype: "rod", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 2, rules: "Button: rod fixes in place, holds 8,000 lb." },
  { name: "Instrument of the Bards (Doss Lute)", category: "supplies", subtype: "instrument", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Charm-focused spells while playing; +bard casting." },
  { name: "Ioun Stone (Mastery)", category: "other", subtype: "", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Orbits head: +1 proficiency bonus." },
  { name: "Ioun Stone (Protection)", category: "other", subtype: "", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Orbits head: +1 AC." },
  { name: "Iron Flask", category: "supplies", subtype: "container", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "Trap an extraplanar creature inside; command it when released." },
  { name: "Javelin", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Simple melee — thrown 30/120." },
  { name: "Javelin of Lightning", category: "gear", subtype: "weapon", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 2, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Throw as lightning bolt: line 4d6 lightning, DC 13 DEX (recharges at dawn)." },
  { name: "Keoghtom's Ointment", category: "consumable", subtype: "alchemical", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, stats: {"heal":"2d8+2","charges":3,"chargesMax":3}, rules: "Apply a dose: heal 2d8+2, cure poison and disease (1d4+1 doses)." },
  { name: "Lance", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, stats: {"dmg":"1d10","dtype":"piercing"}, rules: "Martial melee — reach 10 ft, mounted." },
  { name: "Lantern of Revealing", category: "supplies", subtype: "camp gear", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Light reveals invisible creatures and objects." },
  { name: "Leather Armor", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 10, stats: {"ac":"11 + Dex","armorClass":"light"}, rules: "Light armor — AC 11 + DEX." },
  { name: "Light Crossbow", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 5, stats: {"dmg":"1d8","dtype":"piercing"}, rules: "Simple ranged 80/320." },
  { name: "Light Hammer", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d4","dtype":"bludgeoning"}, rules: "Simple melee — thrown 20/60." },
  { name: "Longbow", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d8","dtype":"piercing"}, rules: "Martial ranged 150/600 — two-handed." },
  { name: "Longsword", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Martial melee — versatile (1d10)." },
  { name: "Luck Blade", category: "gear", subtype: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":1,"charges":3,"chargesMax":3}, rules: "+1 sword, +1 saves; reroll one d20 per dawn; wishes." },
  { name: "Mace", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, stats: {"dmg":"1d6","dtype":"bludgeoning"}, rules: "Simple melee." },
  { name: "Mace of Disruption", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, stats: {"dmg":"1d6","dtype":"bludgeoning"}, rules: "+2d6 radiant vs. fiends/undead; can destroy weak undead (DC 15 WIS)." },
  { name: "Mace of Smiting", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: 4, stats: {"dmg":"1d6","dtype":"bludgeoning","bonus":1}, rules: "+1 mace, +3 vs. constructs; crits deal +7." },
  { name: "Mace of Terror", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, stats: {"dmg":"1d6","dtype":"bludgeoning","charges":3,"chargesMax":3}, rules: "3 charges: 30-ft fear burst, DC 15 WIS." },
  { name: "Mantle of Spell Resistance", category: "accessory", subtype: "cloak", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "ADV on saves vs. spells." },
  { name: "Manual of Bodily Health", category: "papers", subtype: "book", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Read over 6 days: CON +2 permanently." },
  { name: "Maul", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 10, stats: {"dmg":"2d6","dtype":"bludgeoning"}, rules: "Martial melee — two-handed." },
  { name: "Medallion of Thoughts", category: "accessory", subtype: "amulet", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "Cast Detect Thoughts, DC 13 (3 charges, 1d3 at dawn)." },
  { name: "Mirror of Life Trapping", category: "other", subtype: "", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Traps beholders of the mirror in extradimensional cells." },
  { name: "Mithral Armor", category: "gear", subtype: "armor", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Armor without Stealth disadvantage or STR requirement." },
  { name: "Morningstar", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, stats: {"dmg":"1d8","dtype":"piercing"}, rules: "Martial melee." },
  { name: "Necklace of Adaptation", category: "accessory", subtype: "amulet", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Breathe normally in any environment." },
  { name: "Necklace of Fireballs", category: "accessory", subtype: "amulet", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"charges":6,"chargesMax":6}, rules: "Throw beads as Fireballs (DC 15); beads are the charges." },
  { name: "Nine Lives Stealer", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":2,"charges":9,"chargesMax":9}, rules: "+2 sword; crit vs. low-HP target: DC 15 CON or die (9 charges)." },
  { name: "Oathbow", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, stats: {"dmg":"1d8","dtype":"piercing"}, rules: "Sworn enemy: ADV, +3d6 piercing, ignore cover/range." },
  { name: "Oil of Etherealness", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Coat: Etherealness for 1 hour." },
  { name: "Oil of Sharpness", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Coat a weapon: +3 attack and damage for 1 hour." },
  { name: "Oil of Slipperiness", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Coat: Freedom of Movement 8 hrs, or grease a 10-ft square." },
  { name: "Padded Armor", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 8, stats: {"ac":"11 + Dex","armorClass":"light"}, rules: "Light armor — AC 11 + DEX; Stealth DIS." },
  { name: "Pearl of Power", category: "arcana", subtype: "focus", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Regain one expended spell slot (3rd or lower) once per dawn." },
  { name: "Periapt of Health", category: "accessory", subtype: "amulet", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Immune to disease." },
  { name: "Periapt of Proof against Poison", category: "accessory", subtype: "amulet", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Immune to poison damage and the Poisoned condition." },
  { name: "Periapt of Wound Closure", category: "accessory", subtype: "amulet", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Stabilize automatically at 0 HP; double natural healing." },
  { name: "Pike", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 18, stats: {"dmg":"1d10","dtype":"piercing"}, rules: "Martial melee — reach 10 ft, two-handed." },
  { name: "Pipes of Haunting", category: "supplies", subtype: "instrument", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "3 charges: fearsome music, DC 15 WIS or Frightened." },
  { name: "Plate Armor", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 65, stats: {"ac":"18","armorClass":"heavy"}, rules: "Heavy armor — AC 18; STR 15; Stealth DIS." },
  { name: "Plate Armor of Etherealness", category: "gear", subtype: "armor", rarity: "legendary", magic: true, requiresAttunement: true, weight: 65, rules: "Cast Etherealness once per dawn (10 min)." },
  { name: "Portable Hole", category: "supplies", subtype: "container", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cloth unfolds into a 10-ft-deep extradimensional pit." },
  { name: "Potion of Animal Friendship", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: cast Animal Friendship (DC 13) at will for 1 hour." },
  { name: "Potion of Clairvoyance", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Clairvoyance effect." },
  { name: "Potion of Cloud Giant Strength", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Strength 27 for 1 hour." },
  { name: "Potion of Diminution", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Reduce effect for 1d4 hours." },
  { name: "Potion of Fire Breath", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: bonus-action 30-ft fire exhale, DC 13 DEX, 4d6 fire (3 uses, ends after 1 hr)." },
  { name: "Potion of Flying", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: fly speed for 1 hour." },
  { name: "Potion of Frost Giant Strength", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Strength 23 for 1 hour." },
  { name: "Potion of Gaseous Form", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Gaseous Form for 1 hour." },
  { name: "Potion of Growth", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Enlarge effect for 1d4 hours." },
  { name: "Potion of Healing", category: "consumable", subtype: "potion", rarity: "common", magic: true, requiresAttunement: false, weight: 0.5, stats: {"heal":"2d4+2"}, rules: "Drink: regain 2d4+2 HP." },
  { name: "Potion of Healing (Greater)", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, stats: {"heal":"4d4+4"}, rules: "Drink: regain 4d4+4 HP." },
  { name: "Potion of Healing (Superior)", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, stats: {"heal":"8d4+8"}, rules: "Drink: regain 8d4+8 HP." },
  { name: "Potion of Healing (Supreme)", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, stats: {"heal":"10d4+20"}, rules: "Drink: regain 10d4+20 HP." },
  { name: "Potion of Heroism", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: 10 temp HP + Bless for 1 hour." },
  { name: "Potion of Hill Giant Strength", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Strength 21 for 1 hour." },
  { name: "Potion of Invisibility", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Invisible for 1 hour." },
  { name: "Potion of Invulnerability", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: resistance to all damage for 1 minute." },
  { name: "Potion of Mind Reading", category: "consumable", subtype: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Detect Thoughts effect." },
  { name: "Potion of Resistance", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: resistance to one damage type for 1 hour." },
  { name: "Potion of Speed", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Haste for 1 minute, no concentration." },
  { name: "Potion of Vitality", category: "consumable", subtype: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: removes exhaustion, disease, poison; max HP from Hit Dice 24 hrs." },
  { name: "Potion of Water Breathing", category: "consumable", subtype: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: breathe underwater for 1 hour." },
  { name: "Quaal's Feather Token", category: "consumable", subtype: "alchemical", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Single-use token: anchor, bird, fan, swan boat, tree, or whip." },
  { name: "Quarterstaff", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, stats: {"dmg":"1d6","dtype":"bludgeoning"}, rules: "Simple melee — versatile (1d8)." },
  { name: "Quiver of Ehlonna", category: "supplies", subtype: "container", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Three compartments hold far more than they should." },
  { name: "Rapier", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d8","dtype":"piercing"}, rules: "Martial melee — finesse." },
  { name: "Ring Mail", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 40, stats: {"ac":"14","armorClass":"heavy"}, rules: "Heavy armor — AC 14; Stealth DIS." },
  { name: "Ring of Djinni Summoning", category: "accessory", subtype: "ring", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Summon a friendly djinni for 1 hour per dawn." },
  { name: "Ring of Evasion", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "3 charges: turn a failed DEX save into a success." },
  { name: "Ring of Feather Falling", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Fall slowly; no fall damage." },
  { name: "Ring of Free Action", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Ignore difficult terrain; immune to magical speed reduction, Paralyzed, Restrained." },
  { name: "Ring of Invisibility", category: "accessory", subtype: "ring", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Turn Invisible at will." },
  { name: "Ring of Jumping", category: "accessory", subtype: "ring", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Cast Jump on yourself at will." },
  { name: "Ring of Mind Shielding", category: "accessory", subtype: "ring", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Immune to thought-reading; soul enters ring on death." },
  { name: "Ring of Protection", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "+1 AC and saving throws." },
  { name: "Ring of Regeneration", category: "accessory", subtype: "ring", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Regain 1d6 HP every 10 min; regrow lost limbs." },
  { name: "Ring of Resistance", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Resistance to one damage type." },
  { name: "Ring of Shooting Stars", category: "accessory", subtype: "ring", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":6,"chargesMax":6}, rules: "Faerie fire, ball lightning, shooting stars (6 charges)." },
  { name: "Ring of Spell Storing", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Stores up to 5 levels of spells for the wearer to cast." },
  { name: "Ring of Swimming", category: "accessory", subtype: "ring", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Swim speed 40 ft." },
  { name: "Ring of Telekinesis", category: "accessory", subtype: "ring", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Telekinesis at will." },
  { name: "Ring of the Ram", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "Charges: spectral ram attack, 2d10 force per charge (3 charges)." },
  { name: "Ring of Three Wishes", category: "accessory", subtype: "ring", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, stats: {"charges":3,"chargesMax":3}, rules: "Cast Wish (3 charges, not replenished)." },
  { name: "Ring of Water Walking", category: "accessory", subtype: "ring", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Walk on liquid surfaces." },
  { name: "Ring of X-ray Vision", category: "accessory", subtype: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "See through solid matter, 30 ft." },
  { name: "Robe of Eyes", category: "accessory", subtype: "cloak", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "See all directions, Darkvision 120 ft, see invisible." },
  { name: "Robe of Stars", category: "accessory", subtype: "cloak", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"charges":6,"chargesMax":6}, rules: "+1 saves; pluck stars as 5d4 force bolts (6/day); enter Astral Plane." },
  { name: "Robe of the Archmagi", category: "accessory", subtype: "cloak", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "AC 15+DEX; ADV vs. spells; +2 spell DC and attacks." },
  { name: "Robe of Useful Items", category: "accessory", subtype: "cloak", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, stats: {"charges":8,"chargesMax":8}, rules: "Tear off patches that become real objects." },
  { name: "Rod of Absorption", category: "arcana", subtype: "rod", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, rules: "Absorb targeted spells into stored levels (max 50)." },
  { name: "Rod of Alertness", category: "arcana", subtype: "rod", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, rules: "+1 initiative and Perception; detect and protective auras." },
  { name: "Rod of Lordly Might", category: "arcana", subtype: "rod", rarity: "legendary", magic: true, requiresAttunement: true, weight: 2, stats: {"charges":6,"chargesMax":6}, rules: "+3 mace that transforms: flame tongue, axe, spear, ram, ladder." },
  { name: "Rope of Climbing", category: "supplies", subtype: "camp gear", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "60-ft rope moves and knots on command." },
  { name: "Rope of Entanglement", category: "supplies", subtype: "camp gear", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Command: DC 15 DEX or Restrained." },
  { name: "Saddle of the Cavalier", category: "other", subtype: "", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Can't be dislodged from mount; ADV vs. it isn't granted." },
  { name: "Scale Mail", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 45, stats: {"ac":"14 + Dex (max 2)","armorClass":"medium"}, rules: "Medium armor — AC 14 + DEX (max 2); Stealth DIS." },
  { name: "Scimitar", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, stats: {"dmg":"1d6","dtype":"slashing"}, rules: "Martial melee — finesse, light." },
  { name: "Scimitar of Speed", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: 3, stats: {"dmg":"1d6","dtype":"slashing","bonus":2}, rules: "+2 scimitar; attack with it as a bonus action." },
  { name: "Sending Stones", category: "other", subtype: "", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Paired stones: one Sending message per dawn." },
  { name: "Shield", category: "gear", subtype: "shield", rarity: "", magic: false, requiresAttunement: false, weight: 6, stats: {"ac":"+2"}, rules: "+2 AC while wielded." },
  { name: "Shield, +1", category: "gear", subtype: "shield", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 6, stats: {"ac":"+3"}, rules: "+1 bonus to AC (stacks with shield's +2)." },
  { name: "Shield, +2", category: "gear", subtype: "shield", rarity: "rare", magic: true, requiresAttunement: false, weight: 6, stats: {"ac":"+4"}, rules: "+2 bonus to AC." },
  { name: "Shield, +3", category: "gear", subtype: "shield", rarity: "very rare", magic: true, requiresAttunement: false, weight: 6, stats: {"ac":"+5"}, rules: "+3 bonus to AC." },
  { name: "Shortbow", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Simple ranged 80/320." },
  { name: "Shortsword", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Martial melee — finesse, light." },
  { name: "Sickle", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d4","dtype":"slashing"}, rules: "Simple melee." },
  { name: "Sling", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 0, stats: {"dmg":"1d4","dtype":"bludgeoning"}, rules: "Simple ranged 30/120." },
  { name: "Slippers of Spider Climbing", category: "accessory", subtype: "boots", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Climb walls and ceilings, hands free." },
  { name: "Spear", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Simple melee — thrown 20/60, versatile (1d8)." },
  { name: "Spell Scroll (1st Level)", category: "consumable", subtype: "scroll", rarity: "common", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 1st-level spell (DC 13, +5)." },
  { name: "Spell Scroll (2nd Level)", category: "consumable", subtype: "scroll", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 2nd-level spell (DC 13, +5)." },
  { name: "Spell Scroll (3rd Level)", category: "consumable", subtype: "scroll", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 3rd-level spell (DC 15, +7)." },
  { name: "Spell Scroll (4th/5th Level)", category: "consumable", subtype: "scroll", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 4th/5th-level spell (DC 15/17, +7/+9)." },
  { name: "Spell Scroll (6th/7th Level)", category: "consumable", subtype: "scroll", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 6th/7th-level spell (DC 17/18, +9/+10)." },
  { name: "Spell Scroll (Cantrip)", category: "consumable", subtype: "scroll", rarity: "common", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed cantrip; scroll crumbles." },
  { name: "Spellguard Shield", category: "gear", subtype: "shield", rarity: "very rare", magic: true, requiresAttunement: true, weight: 6, rules: "ADV on saves vs. spells; spell attacks vs. you have DIS." },
  { name: "Sphere of Annihilation", category: "other", subtype: "", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "2-ft void that obliterates all matter it touches." },
  { name: "Splint Armor", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 60, stats: {"ac":"17","armorClass":"heavy"}, rules: "Heavy armor — AC 17; STR 15; Stealth DIS." },
  { name: "Staff of Fire", category: "arcana", subtype: "staff", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":10,"chargesMax":10}, rules: "Burning Hands, Fireball, Wall of Fire (10 charges, DC 15)." },
  { name: "Staff of Frost", category: "arcana", subtype: "staff", rarity: "very rare", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":10,"chargesMax":10}, rules: "Ice Storm, Cone of Cold, Wall of Ice (10 charges, DC 15)." },
  { name: "Staff of Healing", category: "arcana", subtype: "staff", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":10,"chargesMax":10}, rules: "Cure Wounds, Lesser Restoration, Mass Cure Wounds (10 charges)." },
  { name: "Staff of Power", category: "arcana", subtype: "staff", rarity: "very rare", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":20,"chargesMax":20}, rules: "+2 quarterstaff & spell attacks; blast spells; retributive strike (20 charges)." },
  { name: "Staff of the Magi", category: "arcana", subtype: "staff", rarity: "legendary", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":50,"chargesMax":50}, rules: "+2 quarterstaff; spell absorption; huge spell list (50 charges)." },
  { name: "Staff of the Python", category: "arcana", subtype: "staff", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, rules: "Throw: becomes a giant constrictor snake." },
  { name: "Staff of Thunder and Lightning", category: "arcana", subtype: "staff", rarity: "very rare", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":10,"chargesMax":10}, rules: "Thunderbolt strikes and storm powers (10 charges)." },
  { name: "Stone of Good Luck", category: "other", subtype: "", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "+1 to ability checks and saving throws." },
  { name: "Studded Leather", category: "gear", subtype: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 13, stats: {"ac":"12 + Dex","armorClass":"light"}, rules: "Light armor — AC 12 + DEX." },
  { name: "Sun Blade", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: 3, stats: {"dmg":"1d8","dtype":"radiant","bonus":2}, rules: "+2 sunlight longsword, radiant damage, +1d8 vs. undead." },
  { name: "Sword of Life Stealing", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Crits: target takes 3d6 extra necrotic; you gain 10 temp HP." },
  { name: "Sword of Sharpness", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Max weapon dice vs. objects; crits can sever limbs." },
  { name: "Sword of Wounding", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Wounds can't heal while it sticks; ongoing 1d4 bleed." },
  { name: "Talisman of Pure Good", category: "accessory", subtype: "amulet", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, stats: {"charges":7,"chargesMax":7}, rules: "Holy talisman; consecrated strikes vs. evil (7 charges)." },
  { name: "Trident", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, stats: {"dmg":"1d6","dtype":"piercing"}, rules: "Martial melee — thrown 20/60, versatile (1d8)." },
  { name: "Trident of Fish Command", category: "gear", subtype: "weapon", rarity: "uncommon", magic: true, requiresAttunement: true, weight: 4, stats: {"charges":3,"chargesMax":3}, rules: "Cast Dominate Beast (DC 15) on water creatures (3 charges)." },
  { name: "Vicious Weapon", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"dmg":"1d8","dtype":"slashing"}, rules: "Crits deal +7 damage." },
  { name: "Vorpal Sword", category: "gear", subtype: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":3}, rules: "+3 sword; ignores slashing resistance; crits can behead." },
  { name: "Wand of Binding", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Hold Monster / Hold Person, DC 17 (7 charges)." },
  { name: "Wand of Enemy Detection", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Sense hostile creatures within 60 ft (7 charges)." },
  { name: "Wand of Fear", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Command or fear cone, DC 15 (7 charges)." },
  { name: "Wand of Fireballs", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Cast Fireball, DC 15; extra charges upcast (7 charges)." },
  { name: "Wand of Lightning Bolts", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Cast Lightning Bolt, DC 15 (7 charges)." },
  { name: "Wand of Magic Detection", category: "arcana", subtype: "wand", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 1, stats: {"charges":3,"chargesMax":3}, rules: "Cast Detect Magic (3 charges, 1d3 at dawn)." },
  { name: "Wand of Magic Missiles", category: "arcana", subtype: "wand", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Cast Magic Missile; more charges = higher level (7 charges)." },
  { name: "Wand of Paralysis", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Ray: DC 15 CON or Paralyzed 1 min (7 charges)." },
  { name: "Wand of Polymorph", category: "arcana", subtype: "wand", rarity: "very rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Cast Polymorph, DC 15 (7 charges)." },
  { name: "Wand of Secrets", category: "arcana", subtype: "wand", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 1, stats: {"charges":3,"chargesMax":3}, rules: "Charge: sense nearest secret door or trap within 30 ft (3 charges)." },
  { name: "Wand of Web", category: "arcana", subtype: "wand", rarity: "uncommon", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Cast Web, DC 15 (7 charges)." },
  { name: "Wand of Wonder", category: "arcana", subtype: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, stats: {"charges":7,"chargesMax":7}, rules: "Random chaotic effect (7 charges)." },
  { name: "War Pick", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d8","dtype":"piercing"}, rules: "Martial melee." },
  { name: "Warhammer", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, stats: {"dmg":"1d8","dtype":"bludgeoning"}, rules: "Martial melee — versatile (1d10)." },
  { name: "Weapon, +1", category: "gear", subtype: "weapon", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":1}, rules: "+1 to attack and damage rolls." },
  { name: "Weapon, +2", category: "gear", subtype: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":2}, rules: "+2 to attack and damage rolls." },
  { name: "Weapon, +3", category: "gear", subtype: "weapon", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, stats: {"dmg":"1d8","dtype":"slashing","bonus":3}, rules: "+3 to attack and damage rolls." },
  { name: "Well of Many Worlds", category: "other", subtype: "", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "Cloth opens a portal to another random plane." },
  { name: "Whip", category: "gear", subtype: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, stats: {"dmg":"1d4","dtype":"slashing"}, rules: "Martial melee — finesse, reach 10 ft." },
  { name: "Winged Boots", category: "accessory", subtype: "boots", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Fly speed equal to walking, 4 hours per day." },
  { name: "Wings of Flying", category: "accessory", subtype: "cloak", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Cloak becomes wings: fly 60 ft for 1 hour per dawn." },

  // ---- SRD adventuring gear (2014 equipment tables, mundane) ----
  { name: "Abacus", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "2 gp", rules: "Beads on rods for quick arithmetic." },
  { name: "Acid (vial)", category: "consumable", subtype: "alchemical", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "25 gp", stats: {"dmg": "2d6", "dtype": "acid"}, rules: "Throw as an improvised weapon (range 20/60): 2d6 acid damage on a hit." },
  { name: "Alchemist's Fire (flask)", category: "consumable", subtype: "alchemical", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "50 gp", stats: {"dmg": "1d4", "dtype": "fire", "dc": "DC 10 Dex"}, rules: "Sticky and burning: 1d4 fire damage at the start of each of the target's turns until a DC 10 Dexterity check puts it out." },
  { name: "Antitoxin (vial)", category: "consumable", subtype: "alchemical", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "50 gp", rules: "Drink for advantage on saving throws against poison for 1 hour." },
  { name: "Backpack", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "2 gp", stats: {"capacity": "30 lb / 1 cubic foot"}, rules: "The adventurer's standard." },
  { name: "Ball Bearings", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "1 gp", rules: "Bag of 1,000; an action spills them over a 10-foot square. A creature crossing must succeed on a DC 10 Dexterity save or fall prone." },
  { name: "Barrel", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 70, value: "2 gp", stats: {"capacity": "40 gallons / 4 cubic feet"}, rules: "" },
  { name: "Basket", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "4 sp", stats: {"capacity": "40 lb / 2 cubic feet"}, rules: "" },
  { name: "Bedroll", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 7, value: "1 gp", rules: "Sleep is a resource too." },
  { name: "Bell", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "1 gp", rules: "" },
  { name: "Blanket", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "5 sp", rules: "" },
  { name: "Block and Tackle", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "1 gp", rules: "Pulleys and rope: hoist up to four times the weight you can normally lift." },
  { name: "Book (blank)", category: "papers", subtype: "book", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "25 gp", rules: "Paper pages waiting for lore, sketches, or accusations." },
  { name: "Glass Bottle", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "2 gp", stats: {"capacity": "1.5 pints"}, rules: "" },
  { name: "Bucket", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "5 cp", stats: {"capacity": "3 gallons / half a cubic foot"}, rules: "" },
  { name: "Caltrops", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "1 gp", rules: "Bag of 20; an action spreads them over a 5-foot square. A creature entering must succeed on a DC 15 Dexterity save or stop moving, take 1 piercing damage, and lose 10 feet of speed until it regains at least 1 hit point." },
  { name: "Candle", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "1 cp", rules: "Bright light 5 feet, dim 5 more, for 1 hour." },
  { name: "Map or Scroll Case", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1 gp", stats: {"capacity": "10 rolled sheets or 5 scrolls"}, rules: "" },
  { name: "Crossbow Bolt Case", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1 gp", stats: {"capacity": "20 bolts"}, rules: "" },
  { name: "Chain (10 feet)", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 10, value: "5 gp", rules: "AC 19, 5 hp; DC 20 Strength to burst." },
  { name: "Chalk (1 piece)", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "1 cp", rules: "" },
  { name: "Chest", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 25, value: "5 gp", stats: {"capacity": "300 lb / 12 cubic feet"}, rules: "" },
  { name: "Climber's Kit", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 12, value: "25 gp", rules: "Pitons, boot tips, gloves, and a harness; anchored as an action, you can't fall more than 25 feet from the anchor point." },
  { name: "Component Pouch", category: "arcana", subtype: "focus", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "25 gp", rules: "Waterproof pockets for all a spell's material components (except those with a listed cost)." },
  { name: "Crowbar", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "2 gp", rules: "Advantage on Strength checks where its leverage can apply." },
  { name: "Dice Set", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "1 sp", rules: "For gambling honestly. Or otherwise." },
  { name: "Disguise Kit", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "25 gp", rules: "Cosmetics, hair dye, and props; proficiency applies to checks to pass as someone else." },
  { name: "Fishing Tackle", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 4, value: "1 gp", rules: "Rod, hooks, line, lures, and patience." },
  { name: "Flask", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "2 cp", stats: {"capacity": "1 pint"}, rules: "" },
  { name: "Grappling Hook", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 4, value: "2 gp", rules: "" },
  { name: "Hammer", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "1 gp", rules: "" },
  { name: "Healer's Kit", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "5 gp", rules: "10 uses; an action stabilizes a creature at 0 hit points without a check." },
  { name: "Herbalism Kit", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "5 gp", rules: "Clippers, mortar and pestle, pouches and vials; proficiency lets you identify plants and craft antitoxin and potions of healing." },
  { name: "Holy Symbol (amulet)", category: "accessory", subtype: "amulet", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "5 gp", rules: "A divine focus for a cleric or paladin, held or worn." },
  { name: "Holy Water (flask)", category: "consumable", subtype: "alchemical", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "25 gp", stats: {"dmg": "2d6", "dtype": "radiant"}, rules: "Throw as an improvised weapon (range 20/60): 2d6 radiant damage to a fiend or undead." },
  { name: "Hourglass", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "25 gp", rules: "" },
  { name: "Hunting Trap", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 25, value: "5 gp", rules: "Saw-toothed ring on a chain: DC 13 Dexterity save or 1d4 piercing damage and movement stopped; DC 13 Strength check to open the jaws." },
  { name: "Ink (1-ounce bottle)", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "10 gp", rules: "" },
  { name: "Ink Pen", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "2 cp", rules: "" },
  { name: "Iron Pot", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 10, value: "2 gp", stats: {"capacity": "1 gallon"}, rules: "" },
  { name: "Iron Spikes (10)", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "1 gp", rules: "" },
  { name: "Jug", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 4, value: "2 cp", stats: {"capacity": "1 gallon"}, rules: "" },
  { name: "Ladder (10-foot)", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 25, value: "1 sp", rules: "" },
  { name: "Lamp", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "5 sp", rules: "Bright light 15 feet, dim 30 more; burns 6 hours on a flask of oil." },
  { name: "Bullseye Lantern", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "10 gp", rules: "Bright light in a 60-foot cone, dim 60 more; burns 6 hours on a flask of oil." },
  { name: "Hooded Lantern", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "5 gp", rules: "Bright light 30 feet, dim 30 more; lower the hood to dim light in 5 feet. Burns 6 hours on a flask of oil." },
  { name: "Lock", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "10 gp", rules: "With key; DC 15 Dexterity check with thieves' tools to pick." },
  { name: "Magnifying Glass", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "100 gp", rules: "Lights fires without flint, and grants advantage on appraising or inspecting small, detailed things." },
  { name: "Manacles", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 6, value: "2 gp", rules: "DC 20 Dexterity to slip, DC 20 Strength to burst; AC 19, 15 hp. Comes with one key." },
  { name: "Merchant's Scale", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "5 gp", rules: "Balance and weights for goods, coin, and the occasional suspicious gem." },
  { name: "Mess Kit", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "2 sp", rules: "Tin cup, plate, and cutlery, nested into a box." },
  { name: "Miner's Pick", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 10, value: "2 gp", rules: "" },
  { name: "Oil (flask)", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1 sp", rules: "Fuels a lantern for 6 hours \u2014 or douse a creature (DC 10 Dexterity to avoid) and ignite for 5 fire damage." },
  { name: "Paper (one sheet)", category: "papers", subtype: "note", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "2 sp", rules: "" },
  { name: "Parchment (one sheet)", category: "papers", subtype: "note", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "1 sp", rules: "" },
  { name: "Perfume (vial)", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "5 gp", rules: "" },
  { name: "Piton", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 0.25, value: "5 cp", rules: "" },
  { name: "Playing Card Set", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "5 sp", rules: "" },
  { name: "Poisoner's Kit", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "50 gp", rules: "Vials, chemicals, and glassware; proficiency applies to crafting and identifying poisons." },
  { name: "Pole (10-foot)", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 7, value: "5 cp", rules: "For prodding things you'd rather not touch." },
  { name: "Portable Ram", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 35, value: "4 gp", rules: "+4 on Strength checks to break down doors; a helper gives you advantage." },
  { name: "Pouch", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "5 sp", stats: {"capacity": "6 lb / one-fifth cubic foot"}, rules: "" },
  { name: "Quiver", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1 gp", stats: {"capacity": "20 arrows"}, rules: "" },
  { name: "Rations (1 day)", category: "consumable", subtype: "food & drink", rarity: "", magic: false, requiresAttunement: false, weight: 2, value: "5 sp", rules: "Jerky, hardtack, dried fruit, and nuts." },
  { name: "Hempen Rope (50 feet)", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 10, value: "1 gp", rules: "2 hp; DC 17 Strength to burst." },
  { name: "Silk Rope (50 feet)", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "10 gp", rules: "2 hp; DC 17 Strength to burst. Lighter and finer than hemp." },
  { name: "Sack", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 0.5, value: "1 cp", stats: {"capacity": "30 lb / 1 cubic foot"}, rules: "" },
  { name: "Sealing Wax", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "5 sp", rules: "" },
  { name: "Shovel", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "2 gp", rules: "" },
  { name: "Signal Whistle", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "5 cp", rules: "" },
  { name: "Sledgehammer", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 10, value: "2 gp", rules: "" },
  { name: "Soap", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "2 cp", rules: "The rarest item in any dungeon." },
  { name: "Spellbook (blank)", category: "arcana", subtype: "spellbook", rarity: "", magic: false, requiresAttunement: false, weight: 3, value: "50 gp", rules: "100 blank vellum pages, ready for a wizard's life's work." },
  { name: "Spyglass", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1,000 gp", rules: "Objects viewed through it are magnified to twice their size." },
  { name: "Tent (two-person)", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 20, value: "2 gp", rules: "" },
  { name: "Thieves' Tools", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "25 gp", rules: "Lockpicks, file, mirror, scissors, pliers; proficiency applies to disarming traps and opening locks." },
  { name: "Tinderbox", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "5 sp", rules: "Flint, steel, and tinder; light a torch as an action, anything else takes a minute." },
  { name: "Torch", category: "supplies", subtype: "camp gear", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1 cp", stats: {"dmg": "1", "dtype": "fire"}, rules: "Burns 1 hour: bright light 20 feet, dim 20 more. As a weapon, 1 fire damage on a hit." },
  { name: "Vial", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: null, value: "1 gp", stats: {"capacity": "4 ounces"}, rules: "" },
  { name: "Waterskin", category: "supplies", subtype: "container", rarity: "", magic: false, requiresAttunement: false, weight: 5, value: "2 sp", stats: {"capacity": "4 pints"}, rules: "Weighs 5 lb full." },
  { name: "Whetstone", category: "supplies", subtype: "tool", rarity: "", magic: false, requiresAttunement: false, weight: 1, value: "1 cp", rules: "" },
];

const RARITY_ORDER = ['', 'common', 'uncommon', 'rare', 'very rare', 'legendary', 'artifact'];

// Prefix matches first, then substring; ties break mundane-before-legendary
// so "sword" surfaces Shortsword before Sword of Sharpness.
export function searchCatalog(query: string, limit = 8): CatalogItem[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  const scored: Array<{ it: CatalogItem; s: number }> = [];
  for (const it of CATALOG) {
    const n = it.name.toLowerCase();
    const at = n.indexOf(q);
    if (at < 0) continue;
    const wordStart = at === 0 || n[at - 1] === ' ' || n[at - 1] === '(';
    scored.push({ it, s: (at === 0 ? 0 : wordStart ? 1 : 2) * 10 + RARITY_ORDER.indexOf(it.rarity) });
  }
  scored.sort((a, b) => a.s - b.s || a.it.name.localeCompare(b.it.name));
  return scored.slice(0, limit).map((x) => x.it);
}
