// Generated from the DM-Screen project's SRD item list (marilynjay/dm-screen,
// src/app.jsx ITEMS_RAW), enriched with SRD 5.1 attunement flags and standard
// weights. Regenerate rather than hand-editing entries wholesale; one-off
// fixes inline are fine.
export interface CatalogItem {
  name: string;
  type: string;
  rarity: string;
  magic: boolean;
  requiresAttunement: boolean;
  weight: number | null;
  rules: string;
}

export const CATALOG: CatalogItem[] = [
  { name: "Alchemy Jug", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 12, rules: "Produces a chosen liquid each day (water, mayonnaise, acid…)." },
  { name: "Ammunition, +1 (each)", type: "ammunition", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "+1 to attack and damage; bonus lost after hit." },
  { name: "Amulet of Health", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Constitution becomes 19." },
  { name: "Amulet of Proof against Detection and Location", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Wearer hidden from divination magic." },
  { name: "Amulet of the Planes", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Plane Shift (DC 15 INT to arrive on target)." },
  { name: "Animated Shield", type: "shield", rarity: "very rare", magic: true, requiresAttunement: true, weight: 6, rules: "Bonus action: shield floats and guards you hands-free." },
  { name: "Armor of Resistance", type: "armor", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Resistance to one damage type while worn." },
  { name: "Armor, +1", type: "armor", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "+1 bonus to AC." },
  { name: "Armor, +2", type: "armor", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "+2 bonus to AC." },
  { name: "Armor, +3", type: "armor", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "+3 bonus to AC." },
  { name: "Bag of Beans", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Plant a bean: wildly random magical effect." },
  { name: "Bag of Holding", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 15, rules: "Holds 500 lb in an extradimensional space." },
  { name: "Bag of Tricks", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Pull a fuzzy object: becomes a random beast until dawn." },
  { name: "Battleaxe", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, rules: "Martial melee — versatile (1d10)." },
  { name: "Bead of Force", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Throw: 3d4 force + sphere imprisons, DC 15 DEX." },
  { name: "Belt of Dwarvenkind", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "CON +2 (max 20), dwarven traits, ADV vs. poison." },
  { name: "Belt of Fire Giant Strength", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Strength becomes 25." },
  { name: "Blowgun", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 1, rules: "Martial ranged 25/100." },
  { name: "Boots of Elvenkind", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Steps make no sound; ADV on Stealth to move silently." },
  { name: "Boots of Levitation", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Levitate on self at will." },
  { name: "Boots of Speed", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Click heels: double speed, no opportunity attacks (10 min/day)." },
  { name: "Boots of Striding and Springing", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Speed 30 ft; jump distance ×3." },
  { name: "Bracers of Archery", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Proficiency with bows; +2 damage with them." },
  { name: "Bracers of Defense", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "+2 AC while unarmored and shieldless." },
  { name: "Breastplate", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 20, rules: "Medium armor — AC 14 + DEX (max 2)." },
  { name: "Brooch of Shielding", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Immune to Magic Missile; resist force damage." },
  { name: "Cape of the Mountebank", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cast Dimension Door once per dawn." },
  { name: "Carpet of Flying", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Flying carpet, up to 80 ft speed." },
  { name: "Chain Mail", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 55, rules: "Heavy armor — AC 16; STR 13; Stealth DIS." },
  { name: "Chain Shirt", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 20, rules: "Medium armor — AC 13 + DEX (max 2)." },
  { name: "Chime of Opening", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Strike: opens one lock/latch within 120 ft (10 uses)." },
  { name: "Circlet of Blasting", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast Scorching Ray (+5) once per dawn." },
  { name: "Cloak of Arachnida", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Spider climb, resist poison, cast Web, immune to webs." },
  { name: "Cloak of Displacement", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Attacks against you have DIS until you take damage." },
  { name: "Cloak of Elvenkind", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Hood up: ADV on Stealth; sight checks to spot you have DIS." },
  { name: "Cloak of Invisibility", type: "wondrous item", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Hood up: Invisible (2 hours of use per day)." },
  { name: "Cloak of Protection", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "+1 AC and saving throws while worn." },
  { name: "Cloak of the Bat", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "ADV on Stealth; fly in dim light; become a bat." },
  { name: "Club", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Simple melee." },
  { name: "Crystal Ball", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: 3, rules: "Cast Scrying (DC 17) while touching it." },
  { name: "Cube of Force", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Barrier cube, 36 charges to power different faces." },
  { name: "Daern's Instant Fortress", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cube grows into an adamantine tower." },
  { name: "Dagger", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 1, rules: "Simple melee — finesse, thrown 20/60." },
  { name: "Dagger of Venom", type: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: 1, rules: "+1 dagger; coat blade: DC 15 CON or 2d10 poison + Poisoned." },
  { name: "Dancing Sword", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Bonus action: sword fights on its own nearby." },
  { name: "Dart", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 0.25, rules: "Simple ranged 20/60 — finesse." },
  { name: "Decanter of Endless Water", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Pours stream/geyser of water on command." },
  { name: "Deck of Illusions", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Draw a card: creates an illusory creature." },
  { name: "Defender", type: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "+3 sword; shift up to +3 between attack and AC each turn." },
  { name: "Dimensional Shackles", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Manacles prevent all extradimensional travel." },
  { name: "Dragon Scale Mail", type: "armor", rarity: "very rare", magic: true, requiresAttunement: true, weight: 45, rules: "+1 scale mail; ADV vs. dragon fear/breath; resist one element." },
  { name: "Dragon Slayer", type: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "+1 sword; +3d6 damage vs. dragons." },
  { name: "Driftglobe", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Hovering globe casts Light or Daylight." },
  { name: "Dust of Disappearance", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Throw: 10-ft radius of creatures turn Invisible for 2d4 minutes." },
  { name: "Dust of Dryness", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Pinch absorbs 15-ft cube of water into a pellet." },
  { name: "Dust of Sneezing and Choking", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cloud: DC 15 CON or Incapacitated, suffocating." },
  { name: "Dwarven Plate", type: "armor", rarity: "very rare", magic: true, requiresAttunement: false, weight: 65, rules: "+2 plate; reduce forced movement by 10 ft." },
  { name: "Dwarven Thrower", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, rules: "+3 warhammer; thrown 20/60, returns; +1d8 (2d8 vs. giants)." },
  { name: "Elemental Gem", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Crush: summon the bound elemental." },
  { name: "Elixir of Health", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: cures disease, poison, and conditions; no HP." },
  { name: "Eversmoking Bottle", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Unstopper: 60-ft radius of heavy smoke." },
  { name: "Eyes of the Eagle", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "ADV on sight-based Perception checks." },
  { name: "Flail", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Martial melee." },
  { name: "Flame Tongue", type: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Command: flaming blade, +2d6 fire damage." },
  { name: "Frost Brand", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "+1d6 cold sword; resist fire; extinguishes flames." },
  { name: "Gauntlets of Ogre Power", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Strength becomes 19." },
  { name: "Gem of Seeing", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "3 charges: Truesight 120 ft for 10 min." },
  { name: "Giant Slayer", type: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "+1 weapon; +2d6 vs. giants, DC 15 STR or prone." },
  { name: "Glaive", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, rules: "Martial melee — reach 10 ft, two-handed." },
  { name: "Glamoured Studded Leather", type: "armor", rarity: "rare", magic: true, requiresAttunement: false, weight: 13, rules: "+1 studded leather; changes appearance on command." },
  { name: "Gloves of Missile Snaring", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Reaction: reduce ranged weapon damage by 1d10+DEX; catch at 0." },
  { name: "Goggles of Night", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Darkvision 60 ft." },
  { name: "Greataxe", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 7, rules: "Martial melee — two-handed." },
  { name: "Greatclub", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 10, rules: "Simple melee, two-handed." },
  { name: "Greatsword", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, rules: "Martial melee — two-handed." },
  { name: "Halberd", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, rules: "Martial melee — reach 10 ft, two-handed." },
  { name: "Half Plate", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 40, rules: "Medium armor — AC 15 + DEX (max 2); Stealth DIS." },
  { name: "Hammer of Thunderbolts", type: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: 10, rules: "+1 (or +3 attuned w/ giant items); giant's bane, thunder crack." },
  { name: "Hand Crossbow", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, rules: "Martial ranged 30/120 — light." },
  { name: "Handaxe", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Simple melee — thrown 20/60." },
  { name: "Hat of Disguise", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Cast Disguise Self at will." },
  { name: "Headband of Intellect", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Intelligence becomes 19." },
  { name: "Heavy Crossbow", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 18, rules: "Martial ranged 100/400 — two-handed." },
  { name: "Helm of Brilliance", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Gem-studded: fire/daylight spells until gems are spent." },
  { name: "Helm of Comprehending Languages", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast Comprehend Languages at will." },
  { name: "Helm of Teleportation", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Teleport (3 charges, 1d3 at dawn)." },
  { name: "Hide Armor", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 12, rules: "Medium armor — AC 12 + DEX (max 2)." },
  { name: "Holy Avenger", type: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "+3 sword; +2d10 radiant vs. fiends/undead; aura of saves." },
  { name: "Horn of Blasting", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Blow: 30-ft cone, 5d6 thunder + Deafened, DC 15 CON." },
  { name: "Horn of Valhalla (Bronze)", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Blow: summons 4d4+4 berserker spirits (once per week)." },
  { name: "Horseshoes of Speed", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Mount's speed +30 ft." },
  { name: "Immovable Rod", type: "rod", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 2, rules: "Button: rod fixes in place, holds 8,000 lb." },
  { name: "Instrument of the Bards (Doss Lute)", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Charm-focused spells while playing; +bard casting." },
  { name: "Ioun Stone (Mastery)", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Orbits head: +1 proficiency bonus." },
  { name: "Ioun Stone (Protection)", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Orbits head: +1 AC." },
  { name: "Iron Flask", type: "wondrous item", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "Trap an extraplanar creature inside; command it when released." },
  { name: "Javelin", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Simple melee — thrown 30/120." },
  { name: "Javelin of Lightning", type: "weapon", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 2, rules: "Throw as lightning bolt: line 4d6 lightning, DC 13 DEX (recharges at dawn)." },
  { name: "Keoghtom's Ointment", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Apply a dose: heal 2d8+2, cure poison and disease (1d4+1 doses)." },
  { name: "Lance", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 6, rules: "Martial melee — reach 10 ft, mounted." },
  { name: "Lantern of Revealing", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Light reveals invisible creatures and objects." },
  { name: "Leather Armor", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 10, rules: "Light armor — AC 11 + DEX." },
  { name: "Light Crossbow", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 5, rules: "Simple ranged 80/320." },
  { name: "Light Hammer", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Simple melee — thrown 20/60." },
  { name: "Longbow", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Martial ranged 150/600 — two-handed." },
  { name: "Longsword", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, rules: "Martial melee — versatile (1d10)." },
  { name: "Luck Blade", type: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "+1 sword, +1 saves; reroll one d20 per dawn; wishes." },
  { name: "Mace", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, rules: "Simple melee." },
  { name: "Mace of Disruption", type: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, rules: "+2d6 radiant vs. fiends/undead; can destroy weak undead (DC 15 WIS)." },
  { name: "Mace of Smiting", type: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: 4, rules: "+1 mace, +3 vs. constructs; crits deal +7." },
  { name: "Mace of Terror", type: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, rules: "3 charges: 30-ft fear burst, DC 15 WIS." },
  { name: "Mantle of Spell Resistance", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "ADV on saves vs. spells." },
  { name: "Manual of Bodily Health", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Read over 6 days: CON +2 permanently." },
  { name: "Maul", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 10, rules: "Martial melee — two-handed." },
  { name: "Medallion of Thoughts", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Cast Detect Thoughts, DC 13 (3 charges, 1d3 at dawn)." },
  { name: "Mirror of Life Trapping", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Traps beholders of the mirror in extradimensional cells." },
  { name: "Mithral Armor", type: "armor", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Armor without Stealth disadvantage or STR requirement." },
  { name: "Morningstar", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, rules: "Martial melee." },
  { name: "Necklace of Adaptation", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Breathe normally in any environment." },
  { name: "Necklace of Fireballs", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Throw beads as Fireballs (DC 15); beads are the charges." },
  { name: "Nine Lives Stealer", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "+2 sword; crit vs. low-HP target: DC 15 CON or die (9 charges)." },
  { name: "Oathbow", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, rules: "Sworn enemy: ADV, +3d6 piercing, ignore cover/range." },
  { name: "Oil of Etherealness", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Coat: Etherealness for 1 hour." },
  { name: "Oil of Sharpness", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Coat a weapon: +3 attack and damage for 1 hour." },
  { name: "Oil of Slipperiness", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Coat: Freedom of Movement 8 hrs, or grease a 10-ft square." },
  { name: "Padded Armor", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 8, rules: "Light armor — AC 11 + DEX; Stealth DIS." },
  { name: "Pearl of Power", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Regain one expended spell slot (3rd or lower) once per dawn." },
  { name: "Periapt of Health", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Immune to disease." },
  { name: "Periapt of Proof against Poison", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Immune to poison damage and the Poisoned condition." },
  { name: "Periapt of Wound Closure", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Stabilize automatically at 0 HP; double natural healing." },
  { name: "Pike", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 18, rules: "Martial melee — reach 10 ft, two-handed." },
  { name: "Pipes of Haunting", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "3 charges: fearsome music, DC 15 WIS or Frightened." },
  { name: "Plate Armor", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 65, rules: "Heavy armor — AC 18; STR 15; Stealth DIS." },
  { name: "Plate Armor of Etherealness", type: "armor", rarity: "legendary", magic: true, requiresAttunement: true, weight: 65, rules: "Cast Etherealness once per dawn (10 min)." },
  { name: "Portable Hole", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cloth unfolds into a 10-ft-deep extradimensional pit." },
  { name: "Potion of Animal Friendship", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: cast Animal Friendship (DC 13) at will for 1 hour." },
  { name: "Potion of Clairvoyance", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Clairvoyance effect." },
  { name: "Potion of Cloud Giant Strength", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Strength 27 for 1 hour." },
  { name: "Potion of Diminution", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Reduce effect for 1d4 hours." },
  { name: "Potion of Fire Breath", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: bonus-action 30-ft fire exhale, DC 13 DEX, 4d6 fire (3 uses, ends after 1 hr)." },
  { name: "Potion of Flying", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: fly speed for 1 hour." },
  { name: "Potion of Frost Giant Strength", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Strength 23 for 1 hour." },
  { name: "Potion of Gaseous Form", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Gaseous Form for 1 hour." },
  { name: "Potion of Growth", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Enlarge effect for 1d4 hours." },
  { name: "Potion of Healing", type: "potion", rarity: "common", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: regain 2d4+2 HP." },
  { name: "Potion of Healing (Greater)", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: regain 4d4+4 HP." },
  { name: "Potion of Healing (Superior)", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: regain 8d4+8 HP." },
  { name: "Potion of Healing (Supreme)", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: regain 10d4+20 HP." },
  { name: "Potion of Heroism", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: 10 temp HP + Bless for 1 hour." },
  { name: "Potion of Hill Giant Strength", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Strength 21 for 1 hour." },
  { name: "Potion of Invisibility", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Invisible for 1 hour." },
  { name: "Potion of Invulnerability", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: resistance to all damage for 1 minute." },
  { name: "Potion of Mind Reading", type: "potion", rarity: "rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Detect Thoughts effect." },
  { name: "Potion of Resistance", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: resistance to one damage type for 1 hour." },
  { name: "Potion of Speed", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: Haste for 1 minute, no concentration." },
  { name: "Potion of Vitality", type: "potion", rarity: "very rare", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: removes exhaustion, disease, poison; max HP from Hit Dice 24 hrs." },
  { name: "Potion of Water Breathing", type: "potion", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 0.5, rules: "Drink: breathe underwater for 1 hour." },
  { name: "Quaal's Feather Token", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Single-use token: anchor, tree, whip, fan, or swan boat." },
  { name: "Quarterstaff", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, rules: "Simple melee — versatile (1d8)." },
  { name: "Quiver of Ehlonna", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Three compartments hold far more than they should." },
  { name: "Rapier", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Martial melee — finesse." },
  { name: "Ring Mail", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 40, rules: "Heavy armor — AC 14; Stealth DIS." },
  { name: "Ring of Djinni Summoning", type: "ring", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Summon a friendly djinni for 1 hour per dawn." },
  { name: "Ring of Evasion", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "3 charges: turn a failed DEX save into a success." },
  { name: "Ring of Feather Falling", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Fall slowly; no fall damage." },
  { name: "Ring of Free Action", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Ignore difficult terrain; immune to magical speed reduction, Paralyzed, Restrained." },
  { name: "Ring of Invisibility", type: "ring", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Turn Invisible at will." },
  { name: "Ring of Jumping", type: "ring", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Cast Jump on yourself at will." },
  { name: "Ring of Mind Shielding", type: "ring", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Immune to thought-reading; soul enters ring on death." },
  { name: "Ring of Protection", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "+1 AC and saving throws." },
  { name: "Ring of Regeneration", type: "ring", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Regain 1d6 HP every 10 min; regrow lost limbs." },
  { name: "Ring of Resistance", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Resistance to one damage type." },
  { name: "Ring of Shooting Stars", type: "ring", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Faerie fire, ball lightning, shooting stars (6 charges)." },
  { name: "Ring of Spell Storing", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Stores up to 5 levels of spells for the wearer to cast." },
  { name: "Ring of Swimming", type: "ring", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Swim speed 40 ft." },
  { name: "Ring of Telekinesis", type: "ring", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Cast Telekinesis at will." },
  { name: "Ring of the Ram", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Charges: spectral ram attack, 2d10 force per charge (3 charges)." },
  { name: "Ring of Three Wishes", type: "ring", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "Cast Wish (3 charges, not replenished)." },
  { name: "Ring of Water Walking", type: "ring", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Walk on liquid surfaces." },
  { name: "Ring of X-ray Vision", type: "ring", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "See through solid matter, 30 ft." },
  { name: "Robe of Eyes", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "See all directions, Darkvision 120 ft, see invisible." },
  { name: "Robe of Stars", type: "wondrous item", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "+1 saves; pluck stars as 5d4 force bolts (6/day); enter Astral Plane." },
  { name: "Robe of the Archmagi", type: "wondrous item", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "AC 15+DEX; ADV vs. spells; +2 spell DC and attacks." },
  { name: "Robe of Useful Items", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Tear off patches that become real objects." },
  { name: "Rod of Absorption", type: "rod", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, rules: "Absorb targeted spells into stored levels (max 50)." },
  { name: "Rod of Alertness", type: "rod", rarity: "very rare", magic: true, requiresAttunement: true, weight: 2, rules: "+1 initiative and Perception; detect and protective auras." },
  { name: "Rod of Lordly Might", type: "rod", rarity: "legendary", magic: true, requiresAttunement: true, weight: 2, rules: "+3 mace that transforms: flame tongue, axe, spear, ram, ladder." },
  { name: "Rope of Climbing", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "60-ft rope moves and knots on command." },
  { name: "Rope of Entanglement", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Command: DC 15 DEX or Restrained." },
  { name: "Saddle of the Cavalier", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Can't be dislodged from mount; ADV vs. it isn't granted." },
  { name: "Scale Mail", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 45, rules: "Medium armor — AC 14 + DEX (max 2); Stealth DIS." },
  { name: "Scimitar", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, rules: "Martial melee — finesse, light." },
  { name: "Scimitar of Speed", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: 3, rules: "+2 scimitar; attack with it as a bonus action." },
  { name: "Sending Stones", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Paired stones: one Sending message per dawn." },
  { name: "Shield", type: "shield", rarity: "", magic: false, requiresAttunement: false, weight: 6, rules: "+2 AC while wielded." },
  { name: "Shield, +1", type: "shield", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 6, rules: "+1 bonus to AC (stacks with shield's +2)." },
  { name: "Shield, +2", type: "shield", rarity: "rare", magic: true, requiresAttunement: false, weight: 6, rules: "+2 bonus to AC." },
  { name: "Shield, +3", type: "shield", rarity: "very rare", magic: true, requiresAttunement: false, weight: 6, rules: "+3 bonus to AC." },
  { name: "Shortbow", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Simple ranged 80/320." },
  { name: "Shortsword", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Martial melee — finesse, light." },
  { name: "Sickle", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Simple melee." },
  { name: "Sling", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 0, rules: "Simple ranged 30/120." },
  { name: "Slippers of Spider Climbing", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Climb walls and ceilings, hands free." },
  { name: "Spear", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, rules: "Simple melee — thrown 20/60, versatile (1d8)." },
  { name: "Spell Scroll (1st Level)", type: "scroll", rarity: "common", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 1st-level spell (DC 13, +5)." },
  { name: "Spell Scroll (2nd Level)", type: "scroll", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 2nd-level spell (DC 13, +5)." },
  { name: "Spell Scroll (3rd Level)", type: "scroll", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed 3rd-level spell (DC 15, +7)." },
  { name: "Spell Scroll (4th/5th Level)", type: "scroll", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed spell (DC 17, +9)." },
  { name: "Spell Scroll (6th/7th Level)", type: "scroll", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed spell (DC 18/19)." },
  { name: "Spell Scroll (Cantrip)", type: "scroll", rarity: "common", magic: true, requiresAttunement: false, weight: null, rules: "Cast the inscribed cantrip; scroll crumbles." },
  { name: "Spellguard Shield", type: "shield", rarity: "very rare", magic: true, requiresAttunement: true, weight: 6, rules: "ADV on saves vs. spells; spell attacks vs. you have DIS." },
  { name: "Sphere of Annihilation", type: "wondrous item", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "2-ft void that obliterates all matter it touches." },
  { name: "Splint Armor", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 60, rules: "Heavy armor — AC 17; STR 15; Stealth DIS." },
  { name: "Staff of Fire", type: "staff", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, rules: "Burning Hands, Fireball, Wall of Fire (10 charges, DC 15)." },
  { name: "Staff of Frost", type: "staff", rarity: "very rare", magic: true, requiresAttunement: true, weight: 4, rules: "Ice Storm, Cone of Cold, Wall of Ice (10 charges, DC 15)." },
  { name: "Staff of Healing", type: "staff", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, rules: "Cure Wounds, Lesser Restoration, Mass Cure Wounds (10 charges)." },
  { name: "Staff of Power", type: "staff", rarity: "very rare", magic: true, requiresAttunement: true, weight: 4, rules: "+2 quarterstaff & spell attacks; blast spells; retributive strike (20 charges)." },
  { name: "Staff of the Magi", type: "staff", rarity: "legendary", magic: true, requiresAttunement: true, weight: 4, rules: "+2 quarterstaff; spell absorption; huge spell list (50 charges)." },
  { name: "Staff of the Python", type: "staff", rarity: "rare", magic: true, requiresAttunement: true, weight: 4, rules: "Throw: becomes a giant constrictor snake." },
  { name: "Staff of Thunder and Lightning", type: "staff", rarity: "very rare", magic: true, requiresAttunement: true, weight: 4, rules: "Thunderbolt strikes and storm powers (10 charges)." },
  { name: "Stone of Good Luck", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "+1 to ability checks and saving throws." },
  { name: "Studded Leather", type: "armor", rarity: "", magic: false, requiresAttunement: false, weight: 13, rules: "Light armor — AC 12 + DEX." },
  { name: "Sun Blade", type: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: 3, rules: "+2 sunlight longsword, radiant damage, +1d8 vs. undead." },
  { name: "Sword of Life Stealing", type: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Crits: target takes 3d6 extra necrotic; you gain 10 temp HP." },
  { name: "Sword of Sharpness", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: true, weight: null, rules: "Max weapon dice vs. objects; crits can sever limbs." },
  { name: "Sword of Wounding", type: "weapon", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Wounds can't heal while it sticks; ongoing 1d4 bleed." },
  { name: "Talisman of Pure Good", type: "wondrous item", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "Holy talisman; consecrated strikes vs. evil (7 charges)." },
  { name: "Trident", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 4, rules: "Martial melee — thrown 20/60, versatile (1d8)." },
  { name: "Trident of Fish Command", type: "weapon", rarity: "uncommon", magic: true, requiresAttunement: true, weight: 4, rules: "Cast Dominate Beast (DC 15) on water creatures (3 charges)." },
  { name: "Vicious Weapon", type: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "Crits deal +7 damage." },
  { name: "Vorpal Sword", type: "weapon", rarity: "legendary", magic: true, requiresAttunement: true, weight: null, rules: "+3 sword; ignores slashing resistance; crits can behead." },
  { name: "Wand of Binding", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Hold Monster / Hold Person, DC 17 (7 charges)." },
  { name: "Wand of Enemy Detection", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Sense hostile creatures within 60 ft (7 charges)." },
  { name: "Wand of Fear", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Command or fear cone, DC 15 (7 charges)." },
  { name: "Wand of Fireballs", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Cast Fireball, DC 15; extra charges upcast (7 charges)." },
  { name: "Wand of Lightning Bolts", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Cast Lightning Bolt, DC 15 (7 charges)." },
  { name: "Wand of Magic Detection", type: "wand", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 1, rules: "Cast Detect Magic (3 charges, 1d3 at dawn)." },
  { name: "Wand of Magic Missiles", type: "wand", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 1, rules: "Cast Magic Missile; more charges = higher level (7 charges)." },
  { name: "Wand of Paralysis", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Ray: DC 15 CON or Paralyzed 1 min (7 charges)." },
  { name: "Wand of Polymorph", type: "wand", rarity: "very rare", magic: true, requiresAttunement: true, weight: 1, rules: "Cast Polymorph, DC 15 (7 charges)." },
  { name: "Wand of Secrets", type: "wand", rarity: "uncommon", magic: true, requiresAttunement: false, weight: 1, rules: "Charge: sense nearest secret door or trap within 30 ft (3 charges)." },
  { name: "Wand of Web", type: "wand", rarity: "uncommon", magic: true, requiresAttunement: true, weight: 1, rules: "Cast Web, DC 15 (7 charges)." },
  { name: "Wand of Wonder", type: "wand", rarity: "rare", magic: true, requiresAttunement: true, weight: 1, rules: "Random chaotic effect (7 charges)." },
  { name: "War Pick", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Martial melee." },
  { name: "Warhammer", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 2, rules: "Martial melee — versatile (1d10)." },
  { name: "Weapon, +1", type: "weapon", rarity: "uncommon", magic: true, requiresAttunement: false, weight: null, rules: "+1 to attack and damage rolls." },
  { name: "Weapon, +2", type: "weapon", rarity: "rare", magic: true, requiresAttunement: false, weight: null, rules: "+2 to attack and damage rolls." },
  { name: "Weapon, +3", type: "weapon", rarity: "very rare", magic: true, requiresAttunement: false, weight: null, rules: "+3 to attack and damage rolls." },
  { name: "Well of Many Worlds", type: "wondrous item", rarity: "legendary", magic: true, requiresAttunement: false, weight: null, rules: "Cloth opens a portal to another random plane." },
  { name: "Whip", type: "weapon", rarity: "", magic: false, requiresAttunement: false, weight: 3, rules: "Martial melee — finesse, reach 10 ft." },
  { name: "Winged Boots", type: "wondrous item", rarity: "uncommon", magic: true, requiresAttunement: true, weight: null, rules: "Fly speed equal to walking, 4 hours per day." },
  { name: "Wings of Flying", type: "wondrous item", rarity: "rare", magic: true, requiresAttunement: true, weight: null, rules: "Cloak becomes wings: fly 60 ft for 1 hour per dawn." },
];

const RARITY_ORDER = ['', 'common', 'uncommon', 'rare', 'very rare', 'legendary', 'artifact'];

// Prefix matches first, then substring; ties break mundane-before-legendary
// so "sword" surfaces Shortsword before Sword of Sharpness.
export function searchCatalog(query: string, limit = 8): CatalogItem[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  const scored: Array<{ it: CatalogItem; s: number }> = [];
  for (const it of CATALOG) {
    const n = it.name.toLowerCase();
    const at = n.indexOf(q);
    if (at < 0) continue;
    const wordStart = at === 0 || n[at - 1] === ' ' || n[at - 1] === '(';
    scored.push({ it, s: (at === 0 ? 0 : wordStart ? 1 : 2) * 10 + RARITY_ORDER.indexOf(it.rarity) });
  }
  scored.sort((a, b) => a.s - b.s || a.it.name.localeCompare(b.it.name));
  return scored.slice(0, limit).map((x) => x.it);
}
